# Generated by Django 5.0.6 on 2024-06-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pallets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('length', models.FloatField()),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ContainerPalletsPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_1', models.CharField(max_length=200)),
                ('position_2', models.CharField(max_length=200)),
                ('position_3', models.CharField(max_length=200)),
                ('pallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pallets.pallet')),
                ('container_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containerTypes.containers')),
            ],
        ),
    ]
