# Generated by Django 5.0.6 on 2024-06-18 02:49

from django.db import migrations

def add_containers(apps, schema_editor):
    container = apps.get_model("containerTypes", "Containers")
    teu = container(name='TEU', length=6.09, width=2.44, height=2.59, weight=2.33, volume=38.45)
    teu.save()
    feu = container(name='FEU', length=12.19, width=2.44, height=2.59, weight=3.80, volume=76.99)
    feu.save()
    teuhb = container(name='TEUHB', length=6.09, width=2.44, height=2.90, weight=2.63, volume=42.98)
    teuhb.save()    
    feuhb = container(name='FEUHB', length=12.19, width=2.44, height=2.90, weight=3.91, volume=86.05)
    feuhb.save()
    refeer = container(name='Refeer HB', length=12.19, width=2.44, height=2.90, weight=5.20, volume=86.05)
    refeer.save()
    
def remove_containers(apps, schema_editor):
    container = apps.get_model("containerTypes", "Containers")
    teu = container.objects.get(name='TEU')
    teu.delete()
    feu = container.objects.get(name='FEU')
    feu.delete()
    teuhb = container.objects.get(name='TEUHB')
    teuhb.delete()
    feuhb = container.objects.get(name='FEUHB')
    feuhb.delete()
    refeer = container.objects.get(name='Refeer HB')
    refeer.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('containerTypes', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(add_containers, reverse_code=remove_containers),
    ]
