# Generated by Django 5.0.6 on 2024-06-26 02:07

from django.db import migrations

def add_positions(apps, schema_editor):
    positions = apps.get_model("containerTypes", "ContainerPalletsPosition")
    Pallet = apps.get_model("pallets", "Pallet")
    Container = apps.get_model("containerTypes", "Containers")  # Add this line
    
    pallet1 = Pallet.objects.get(id=1)
    pallet2 = Pallet.objects.get(id=2)
    
    container1 = Container.objects.get(id=1)  
    container2 = Container.objects.get(id=2)  
    container3 = Container.objects.get(id=3)
    container4 = Container.objects.get(id=4)
    container5 = Container.objects.get(id=5)
    
    position11 = positions(pallet_id=pallet1, container_id=container1, position_1='{"large": 5, "width": 2, "total": 10}', position_2='{"large": 6, "width": 2, "total": 12}', position_3='{"large": null, "width": null, "total": 11}')
    position11.save()
    position12 = positions(pallet_id=pallet1, container_id=container2, position_1='{"large": 10, "width": 2, "total": 20}', position_2='{"large": 12, "width": 2, "total": 24}', position_3='{"large": null, "width": null, "total": 22}')
    position12.save()
    position13 = positions(pallet_id=pallet1, container_id=container3, position_1='{"large": 5, "width": 2, "total": 10}', position_2='{"large": 6, "width": 2, "total": 12}', position_3='{"large": null, "width": null, "total": 11}')
    position13.save()
    position14 = positions(pallet_id=pallet1, container_id=container4, position_1='{"large": 10, "width": 2, "total": 20}', position_2='{"large": 12, "width": 2, "total": 24}', position_3='{"large": null, "width": null, "total": 22}')
    position14.save()
    position15 = positions(pallet_id=pallet1, container_id=container5, position_1='{"large": 10, "width": 2, "total": 20}', position_2='{"large": 12, "width": 2, "total": 24}', position_3='{"large": null, "width": null, "total": 22}')
    position15.save()

    position21 = positions(pallet_id=pallet2, container_id=container1, position_1='{"large": 6, "width": 3, "total": 18}', position_2='{"large": 7, "width": 2, "total": 14}', position_3='{"large": null, "width": null, "total": 13}')
    position21.save()
    position22 = positions(pallet_id=pallet2, container_id=container2, position_1='{"large": 12, "width": 3, "total": 36}', position_2='{"large": 15, "width": 2, "total": 30}', position_3='{"large": null, "width": null, "total": 27}')
    position22.save()
    position23 = positions(pallet_id=pallet2, container_id=container3, position_1='{"large": 6, "width": 3, "total": 18}', position_2='{"large": 7, "width": 2, "total": 14}', position_3='{"large": null, "width": null, "total": 13}')
    position23.save()
    position24 = positions(pallet_id=pallet2, container_id=container4, position_1='{"large": 12, "width": 3, "total": 36}', position_2='{"large": 15, "width": 2, "total": 30}', position_3='{"large": null, "width": null, "total": 27}')
    position24.save()
    position25 = positions(pallet_id=pallet2, container_id=container5, position_1='{"large": 12, "width": 3, "total": 36}', position_2='{"large": 15, "width": 2, "total": 30}', position_3='{"large": null, "width": null, "total": 27}')
    position25.save()

class Migration(migrations.Migration):

    dependencies = [
        ('containerTypes', '0002_auto_20240626_1109'),
    ]

    operations = [
        migrations.RunPython(add_positions),
    ]

