# Generated by Django 5.0.6 on 2024-06-17 20:51

from django.db import migrations


def add_pallets(apps, schema_editor):
    pallets = apps.get_model("pallets", "Pallet")
    amr = pallets(name="AMR", width=1.0, height=0.14, length=1.2, weight=14.0, volume=0.18)
    amr.save()
    eur = pallets(name="EUR", width=0.8, height=0.14, length=1.0, weight=12.0, volume=0.12)
    eur.save()

def remove_pallets(apps, schema_editor):
    Pallet = apps.get_model("pallets", "Pallet")
    for name in ["AMR", "EUR"]:
        try:
            pallet = Pallet.objects.get(name=name)
            pallet.delete()
        except Pallet.DoesNotExist:
            pass
class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0001_initial'),
    ]

    operations = [

        migrations.RunPython(add_pallets, reverse_code=remove_pallets),
    ]
